apiVersion: v1
kind: Service
metadata:
  name: laravel
spec:
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
        - name: app
          image: gabrielfcisco/laravel:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: app-storage
              mountPath: /var/www
          command: ["/bin/sh", "-c"]
          args:
            - |
              cd /var/www &&
              composer install &&
              php artisan migrate &&
              php artisan serve --host=0.0.0.0 --port=8000
      volumes:
        - name: app-storage
          hostPath:
            path: /home/gabriel/Faculdade/desenvolvimento_apps/clinica-divertidamente
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.30
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "laravel"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "root"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          hostPath:
            path: /home/gabriel/Faculdade/desenvolvimento_apps/clinica-divertidamente/.docker/mysql/data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue
  template:
    metadata:
      labels:
        app: vue
    spec:
      containers:
        - name: vue
          image: node:latest
          command: ["sh", "-c"]
          args: ["cd /app && npm install && npm run build && sleep infinity"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: app-storage
              mountPath: /app
      volumes:
        - name: app-storage
          hostPath:
            path: /home/gabriel/Faculdade/desenvolvimento_apps/clinica-divertidamente
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          env:
            - name: PMA_ARBITRARY
              value: "1"
            - name: PMA_HOST
              value: "mysql"
            - name: PMA_USER
              value: "user"
            - name: PMA_PASSWORD
              value: "root"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: app-storage
              mountPath: /var/www
      volumes:
        - name: nginx-config
          hostPath:
            path: /home/gabriel/Faculdade/desenvolvimento_apps/clinica-divertidamente/.docker/nginx
        - name: app-storage
          hostPath:
            path: /home/gabriel/Faculdade/desenvolvimento_apps/clinica-divertidamente
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
